config/routes.rb
Rails.application.routes.draw do
  resources :courses
  resources :course_contents

  devise_for :users

  authenticated :user do
    root 'user#dash', as: :authenticated_root
  end

  unauthenticated :user do
    devise_scope :user do 
      get "/" => "devise/sessions#new"
    end
  end

end

app/models/course.rb
class Course < ActiveRecord::Base
	 has_many :course_content
end

app/models/course_content.rb
class CourseContent < ActiveRecord::Base
    belongs_to :course

end

app/models/pdf.rb
class Pdf < ActiveRecord::Base
	belongs_to :course_content

	has_attached_file :uploaded_file
  
	validates_attachment_size :uploaded_file, :less_than => 10.megabytes   
	validates_attachment_presence :uploaded_file
	validates_attachment_file_name :uploaded_file, :matches => [/pdf\Z/]

	def file_name 
    	uploaded_file_file_name 
	end
end

app/models/post.rb
class Post < CourseContent
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :courses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # Prevent CSRF attacks by raising an exception.
    # For APIs, you may want to use :null_session instead.
    protect_from_forgery with: :exception
    before_action :authenticate_user!

    before_action :find_all_courses

    private
            def find_all_courses
                puts "courses"
                @courses = Course.all
            end
end

app/controllers/course_contents_controller.rb
require 'uri'

class CourseContentsController < ApplicationController

    def create
        @course_content = CourseContent.new(course_content_params)
        @course_content.save
        redirect_to @course_content.course
    end

    private
        def course_content_params
            params.require(:course_content).permit(:course_id, :name, :description, :body, :uploaded_file)
        end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @courses = Course.all
    respond_with(@courses)
  end

  def show
    @course_content = CourseContent.new
  end

  def new
    @course = Course.new
    respond_with(@course)
  end

  def edit
  end

  def create
    @course = Course.new(course_params)
    @course.save
    respond_with(@course)
  end

  def update
    @course.update(course_params)
    respond_with(@course)
  end

  def destroy
    @course.destroy
    respond_with(@course)
  end

  private
    def set_course
      @course = Course.find(params[:id])
    end

    def course_params
      params.require(:course).permit(:name, :code, :semester)
    end
end

app/controllers/pdfs_controller.rb
class PdfsController < ApplicationController
  before_action :set_pdf, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @pdfs = Pdf.all
    respond_with(@pdfs)
  end

  def show
    respond_with(@pdf)
  end

  def new
    @pdf = Pdf.new
    respond_with(@pdf)
  end

  def edit
  end

  def create
    def create
        @pdf = PDF.new(course_content_params)
        @pdf.save
        redirect_to @pdf.course
    end
  end

  def update
    @pdf.update(pdf_params)
    respond_with(@pdf)
  end

  def destroy
    @pdf.destroy
    respond_with(@pdf)
  end

  private
    def set_pdf
      @pdf = Pdf.find(params[:id])
    end

    def pdf_params
      params.require(:pdf).permit(:course_id, :uploaded_file)
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
    

    # The dash will use Nobel prize-winning algorithms to aggregate all relevant
    # content for a User and display it in a neat timeline form.
    def dash
        
    end

    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/course_content_helper.rb
module CourseContentHelper

	def embed_doc(body)
		return "" if body.nil?
    	youtube_id = parse_for_url(body)
    	if youtube_id
			return	content_tag(:iframe, nil, src: "//www.youtube.com/embed/#{youtube_id}")
		else

		end
	end

	def link_attachment(uploaded_file)
		return "" if uploaded_file.nil?
		content_tag(:p, link_to(cc.uploaded_file_file_name, cc.uploaded_file.url))
	end

    def parse_for_url(body)
		urls = URI.extract(body)
		if urls.length > 0 
			urls.each do |x|
				return x.split("v=").last if x.include? "youtube.com/watch"
			end
		end
	end
end

app/helpers/pdfs_helper.rb
module PdfsHelper
end

app/helpers/video_helper.rb
module VideoHelper

  def embed(youtube_url)
    youtube_id = youtube_url.split("=").last
    content_tag(:iframe, nil, src: "//www.youtube.com/embed/#{youtube_id}")
  end

end  

app/views/courses/_form.html.erb
<%= form_for(@course) do |f| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :code %><br>
    <%= f.text_field :code %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing course</h1>

<%= render 'form' %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<h1>Listing courses</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Code</th>
      <th>Semester</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.name %></td>
        <td><%= course.code %></td>
        <td><%= link_to 'Show', course %></td>
        <td><%= link_to 'Edit', edit_course_path(course) %></td>
        <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Course', new_course_path %>

app/views/courses/new.html.erb
<h1>New course</h1>

<%= render 'form' %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <h1><%= @course.name %></h1>
</p>

<p>
  <strong>Code:</strong>
  <h3><%= @course.code %></h3>
</p>

<h1>New Post</h1>
<%= form_for @course_content, :html => {:multipart => true} do |f| %>
    <%= f.hidden_field :course_id, value: @course.id %>

    Comment: <%= f.text_area :body %>
    <%= f.label :uploaded_file, "Attach" %><br /> 
    <%= f.file_field :uploaded_file %> 
    <%= f.submit %>
<% end %>

<h1>Course Content</h1>
<% if @course.course_content.length > 0 %>
     <% @course.course_content.each do |cc| %>
        <p><%= cc.body %></p>
        <p><%= embed_doc(cc.body)%> </p>
        <p><%= link_to cc.uploaded_file_file_name, cc.uploaded_file.url %></p>
    <% end %>
<% else %>
    <p>There is no content.</p>
<% end %>

app/views/layouts/_navbar.html.erb
<header>
    <%= link_to authenticated_root_path do %>
        <%= image_tag "Logo_Deanlist_white.png" %>
    <% end %>

    <%# Courses list %>
    <% if user_signed_in? %>
        <span class="dropdown">
            <a href="#" data-toggle="dropdown">Courses</a>
            
            <ul class="dropdown-menu">
                <% if @courses.length > 0 %>
                    <% @courses.each do |course| %>
                        <li><%= link_to course.name, course %></li>
                    <% end %>
                <% else %>
                    <li>You have no courses. <%= link_to "Add one now.", new_course_path %></li>
                <% end %>
            </ul>
        </span>
    <% end %>

    <%# Authentication area %>
    <div class="right">
        <% if user_signed_in? %>
            <%= link_to current_user.email, edit_user_registration_path %>
            <%= link_to "Logout", destroy_user_session_path, method: "DELETE" %>
        <% else %>
            <%= link_to "Register now", new_user_registration_path %>
        <% end %>
    </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DeansList</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
    <link href='http://fonts.googleapis.com/css?family=Raleway:400,200|Open+Sans:400,300,700' rel='stylesheet' type='text/css'>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>

  <%= csrf_meta_tags %>
</head>
<body>
    <%# Render the header %>
    <%= render "layouts/navbar" %>

    <%# Render any flash messages %>
	<% if notice %>
  	     <p class="alert alert-success"><%= notice %></p>
	<% end %>
    <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
	<% end %>

    <%# Render the page body %>
    <%= yield %>
</body>
</html>

app/views/pdfs/_form.html.erb
<%= form_for(@pdf, :multipart => true) do |f| %> 

    <p> 
        <%= f.label :uploaded_file, "File" %><br /> 
        <%= f.file_field :uploaded_file %> 
      </p> 
  <p><%= f.submit "Upload" %></p> 
<% end %>

app/views/pdfs/edit.html.erb
<h1>Editing pdf</h1>

<%= render 'form' %>

<%= link_to 'Show', @pdf %> |
<%= link_to 'Back', pdfs_path %>

app/views/pdfs/index.html.erb
<h1>Uploaded PDF's</h1>
<table> 
  <tr> 
    <th>Uploaded Files</th> 
  </tr> 
  <% for pdf in @pdfs %> 
    <tr> 
      <td><%= link_to pdf.uploaded_file_file_name, pdf.uploaded_file.url %></td> 
      <td><%= link_to "Show", pdf %></td> 
      <td><%= link_to "Edit", edit_pdf_path(pdf) %></td> 
      <td><%= link_to "Destroy", pdf, :confirm => 'Are you sure?', :method => :delete %></td> 
    </tr> 
  <% end %> 
</table> 
<p><%= link_to "New Asset", new_pdf_path %></p>

app/views/pdfs/new.html.erb
<h1>New pdf</h1>

<%= render 'form' %>

<%= link_to 'Back', pdfs_path %>

app/views/pdfs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Course:</strong>
  <%= @pdf.course_id %>
</p>

<%= link_to 'Edit', edit_pdf_path(@pdf) %> |
<%= link_to 'Back', pdfs_path %>

app/views/user/dash.html.erb
<h1>My Dashboard</h1>

<div class="feed">
    <article>
        <h1>I found this video educational</h1>
        <span class="coursecode">MUS2122</span>
        <span class="author">by William Duvall,</span>
        <span class="date">An hour ago</span>

        <div class="content">
            <iframe src="https://www.youtube.com/embed/OM4mVGJkp6A" frameborder="0" allowfullscreen></iframe>
        </div>
    </article>

    <article class="related">
        <h1>We thought you might like:</h1>
        <div class="content">
            <%= image_tag "http://www.placecage.com/103/90" %>
            <%= image_tag "http://www.placecage.com/103/91" %>
            <%= image_tag "http://www.placecage.com/103/89" %>
            <%= image_tag "http://www.placecage.com/104/91" %>
        </div>
    </article>

    <article>
        <h1>Mnemonics for modes?</h1>
        <span class="coursecode">MUS2101</span>
        <span class="author">by I. M. Beethoven,</span>
        <span class="date">Yesterday</span>

        <div class="content">
            <p>Dose anybody have any good mnemonics for modes? I cant for the life of me remember witch order they go in lol!!</p>
        </div>

        <div class="comments">
            Comments:
            <div><span class="commenter">M. Naught Beethoven</span>Try this: Don't Particularly Like Modes A Lot (Ionian, Dorian, Phygrian, Lydian, Myxolidian, Aolian, Locrian).</div>
            <div><span class="commenter">I. M. Beethoven</span>OMG Thanx soo Much!!!</div>
            <div><input type="text" class="form-control" placeholder="Write a new comment" /></div>
        </div>
    </article>
    <article>
        <h1>Anyone in Fillion's saxophone class - I heard he gives extra points if you can pull this off:</h1>
        <span class="coursecode">SAX101</span>
        <span class="author">by Jeff Coffin,</span>
        <span class="date">Friday</span>

        <div class="content">
            <iframe src="https://www.youtube.com/embed/gLnjWe4V1hA" frameborder="0" allowfullscreen></iframe>
        </div>
    </article>
</div>